// Copyright 2018 Fredrik Portström <https://portstrom.com>
// This is free software distributed under the terms specified in
// the file LICENSE at the top-level directory of this distribution.

/// Allocates and returns a configuration for Parse Wiki Text suitable for parsing the Czech language edition of Wiktionary.
///
/// The same configuration should be reused when parsing multiple articles for optimal performance.
pub fn create_configuration() -> ::parse_wiki_text::Configuration {
    ::parse_wiki_text::Configuration::new(&::parse_wiki_text::ConfigurationSource {
        category_namespaces: &["category", "kategorie"],
        extension_tags: &[
            "categorytree",
            "ce",
            "charinsert",
            "chem",
            "gallery",
            "graph",
            "hiero",
            "imagemap",
            "indicator",
            "inputbox",
            "mapframe",
            "maplink",
            "math",
            "nowiki",
            "poem",
            "pre",
            "ref",
            "references",
            "score",
            "section",
            "source",
            "splist",
            "syntaxhighlight",
            "templatedata",
            "timeline",
        ],
        file_namespaces: &["file", "image", "obrázok", "soubor"],
        link_trail:
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzáéíóúýčďěňřšťůž",
        magic_words: &[
            "BEZEDITOVATČÁST",
            "BEZGALERIE",
            "BEZGALÉRIE",
            "BEZKONVERZENADPISU",
            "BEZKONVERZEOBSAHU",
            "BEZLINKUPŘIDATKOMENTÁŘ",
            "BEZOBSAHU",
            "DISAMBIG",
            "FORCETOC",
            "HIDDENCAT",
            "INDEX",
            "INDEXOVAT",
            "LINKPŘIDATKOMENTÁŘ",
            "NEINDEXOVAT",
            "NEUPRAVOVAŤSEKCIE",
            "NEWSECTIONLINK",
            "NOCC",
            "NOCOLLABORATIONHUBTOC",
            "NOCONTENTCONVERT",
            "NOEDITSECTION",
            "NOGALLERY",
            "NOGLOBAL",
            "NOINDEX",
            "NONEWSECTIONLINK",
            "NOTC",
            "NOTITLECONVERT",
            "NOTOC",
            "OBSAH",
            "SKRYTÁKAT",
            "SKRYTÁKATEGÓRIA",
            "SKRÝTKAT",
            "STATICKÉPŘESMĚROVÁNÍ",
            "STATICREDIRECT",
            "TOC",
            "VYNÚTIŤOBSAH",
            "VŽDYOBSAH",
        ],
        protocols: &[
            "//",
            "bitcoin:",
            "ftp://",
            "ftps://",
            "geo:",
            "git://",
            "gopher://",
            "http://",
            "https://",
            "irc://",
            "ircs://",
            "magnet:",
            "mailto:",
            "mms://",
            "news:",
            "nntp://",
            "redis://",
            "sftp://",
            "sip:",
            "sips:",
            "sms:",
            "ssh://",
            "svn://",
            "tel:",
            "telnet://",
            "urn:",
            "worldwind://",
            "xmpp:",
        ],
        redirect_magic_words: &["PŘESMĚRUJ", "REDIRECT", "presmeruj"],
    })
}
