// Copyright 2018 Fredrik Portström <https://portstrom.com>
// This is free software distributed under the terms specified in
// the file LICENSE at the top-level directory of this distribution.

/// Identifier for a language.
#[allow(missing_docs)]
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Language {
    Aa,
    Aau,
    Ab,
    Abe,
    Ady,
    Af,
    Ain,
    Ak,
    Ale,
    Als,
    Alt,
    Am,
    An,
    Ang,
    Ar,
    Arc,
    Arn,
    Arz,
    As,
    Ast,
    Atv,
    Ay,
    Az,
    Azb,
    Ba,
    Bal,
    Bar,
    Bcl,
    Be,
    Bem,
    Bg,
    Bi,
    Bjn,
    Bm,
    Bn,
    Bo,
    Bpy,
    Br,
    Bs,
    Bxr,
    Ca,
    Cab,
    Ce,
    Ceb,
    Ch,
    Chk,
    Chp,
    Chr,
    Cim,
    Ckb,
    Co,
    Cpf,
    Cps,
    Crh,
    Cs,
    Csb,
    Cu,
    Cv,
    Cy,
    Da,
    De,
    Dgd,
    Dje,
    Dlm,
    Dsb,
    Dv,
    Dz,
    Ee,
    Egy,
    El,
    En,
    Eo,
    Es,
    Et,
    Eu,
    Ext,
    Fa,
    Fi,
    Fil,
    Fj,
    Fkv,
    Fo,
    Fr,
    Frp,
    Frr,
    Fur,
    Fy,
    Ga,
    Gad,
    Gag,
    Gd,
    Gil,
    Gl,
    Gmh,
    Gml,
    Gn,
    Got,
    Grc,
    Gsw,
    Gu,
    Guz,
    Gv,
    Ha,
    Hak,
    Haw,
    He,
    Hi,
    Hil,
    Hit,
    Hnd,
    Hr,
    Hsb,
    Ht,
    Hu,
    Hy,
    Ia,
    Id,
    Ie,
    Ig,
    Ilo,
    Inh,
    Io,
    Is,
    It,
    Iu,
    Izh,
    Ja,
    Jbo,
    Jpa,
    Jv,
    Ka,
    Kaa,
    Kab,
    Kea,
    Kim,
    Kjh,
    Kk,
    Kl,
    Km,
    Kn,
    Ko,
    Kok,
    Kos,
    Krl,
    Ku,
    Kv,
    Kw,
    Ky,
    La,
    Lad,
    LadCyrl,
    LadHebr,
    LadLatn,
    Lb,
    Lbe,
    Lg,
    Li,
    Lij,
    Liv,
    Lld,
    Lmo,
    Ln,
    Lo,
    Lt,
    Ltg,
    Lv,
    Mas,
    Mdf,
    Mg,
    Mh,
    Mi,
    Mk,
    Ml,
    Mn,
    Mnc,
    Mr,
    Mrh,
    Ms,
    Mt,
    Mwl,
    Mww,
    My,
    Myv,
    Na,
    Nah,
    Nan,
    Nap,
    Nb,
    Nci,
    Nds,
    Ne,
    Ng,
    Nij,
    Niu,
    Nl,
    Nn,
    No,
    Nov,
    Nrf,
    Nso,
    Nv,
    Ny,
    Oc,
    Oj,
    Om,
    Or,
    Os,
    Pa,
    Pam,
    Pap,
    Pau,
    Pl,
    Pms,
    Pnb,
    Pon,
    Pox,
    Prg,
    Ps,
    Pt,
    Qu,
    Rap,
    Rar,
    Rm,
    Rmy,
    Rn,
    Ro,
    Rom,
    Rtm,
    Ru,
    Rue,
    Rup,
    Rw,
    Ryu,
    Sa,
    Sah,
    Sc,
    Scn,
    Sco,
    Sd,
    Se,
    Sgd,
    Sgs,
    Sh,
    Si,
    Sk,
    Sl,
    Sli,
    Sm,
    Sn,
    So,
    Sq,
    Sr,
    SrCyrl,
    SrLatn,
    Src,
    Sro,
    Ss,
    Su,
    Sux,
    Sv,
    Sw,
    Syr,
    Szl,
    Ta,
    Tah,
    Te,
    Tg,
    Th,
    Ti,
    Tk,
    Tkl,
    Tl,
    Tlh,
    Tmr,
    Tn,
    To,
    Tog,
    Tr,
    Ts,
    Tt,
    Tum,
    Tvl,
    Tw,
    Ty,
    Tyv,
    Udm,
    Ug,
    Uk,
    Ur,
    Uz,
    Vec,
    Vep,
    Vi,
    Vo,
    Vot,
    Vro,
    Wa,
    Wah,
    War,
    Wo,
    Wym,
    Xal,
    Xcu,
    Xh,
    Xmf,
    Yi,
    Yo,
    Yue,
    Zh,
    Zu,
}

impl Language {
    /// Returns the language corresponding to the given language code if any.
    pub fn from_language_code(language_code: &str) -> Option<Self> {
        Some(match language_code {
            "aa" => Language::Aa,
            "aau" => Language::Aau,
            "ab" => Language::Ab,
            "abe" => Language::Abe,
            "ady" => Language::Ady,
            "af" => Language::Af,
            "ain" => Language::Ain,
            "ak" => Language::Ak,
            "ale" => Language::Ale,
            "als" => Language::Als,
            "alt" => Language::Alt,
            "am" => Language::Am,
            "an" => Language::An,
            "ang" => Language::Ang,
            "ar" => Language::Ar,
            "arc" => Language::Arc,
            "arn" => Language::Arn,
            "arz" => Language::Arz,
            "as" => Language::As,
            "ast" => Language::Ast,
            "atv" => Language::Atv,
            "ay" => Language::Ay,
            "az" => Language::Az,
            "azb" => Language::Azb,
            "ba" => Language::Ba,
            "bal" => Language::Bal,
            "bar" => Language::Bar,
            "bcl" => Language::Bcl,
            "be" => Language::Be,
            "bem" => Language::Bem,
            "bg" => Language::Bg,
            "bi" => Language::Bi,
            "bjn" => Language::Bjn,
            "bm" => Language::Bm,
            "bn" => Language::Bn,
            "bo" => Language::Bo,
            "bpy" => Language::Bpy,
            "br" => Language::Br,
            "bs" => Language::Bs,
            "bxr" => Language::Bxr,
            "ca" => Language::Ca,
            "cab" => Language::Cab,
            "ce" => Language::Ce,
            "ceb" => Language::Ceb,
            "ch" => Language::Ch,
            "chk" => Language::Chk,
            "chp" => Language::Chp,
            "chr" => Language::Chr,
            "cim" => Language::Cim,
            "ckb" => Language::Ckb,
            "co" => Language::Co,
            "cpf" => Language::Cpf,
            "cps" => Language::Cps,
            "crh" => Language::Crh,
            "cs" => Language::Cs,
            "csb" => Language::Csb,
            "cu" => Language::Cu,
            "cv" => Language::Cv,
            "cy" => Language::Cy,
            "da" => Language::Da,
            "de" => Language::De,
            "dgd" => Language::Dgd,
            "dje" => Language::Dje,
            "dlm" => Language::Dlm,
            "dsb" => Language::Dsb,
            "dv" => Language::Dv,
            "dz" => Language::Dz,
            "ee" => Language::Ee,
            "egy" => Language::Egy,
            "el" => Language::El,
            "en" => Language::En,
            "eo" => Language::Eo,
            "es" => Language::Es,
            "et" => Language::Et,
            "eu" => Language::Eu,
            "ext" => Language::Ext,
            "fa" => Language::Fa,
            "fi" => Language::Fi,
            "fil" => Language::Fil,
            "fj" => Language::Fj,
            "fkv" => Language::Fkv,
            "fo" => Language::Fo,
            "fr" => Language::Fr,
            "frp" => Language::Frp,
            "frr" => Language::Frr,
            "fur" => Language::Fur,
            "fy" => Language::Fy,
            "ga" => Language::Ga,
            "gad" => Language::Gad,
            "gag" => Language::Gag,
            "gd" => Language::Gd,
            "gil" => Language::Gil,
            "gl" => Language::Gl,
            "gmh" => Language::Gmh,
            "gml" => Language::Gml,
            "gn" => Language::Gn,
            "got" => Language::Got,
            "grc" => Language::Grc,
            "gsw" => Language::Gsw,
            "gu" => Language::Gu,
            "guz" => Language::Guz,
            "gv" => Language::Gv,
            "ha" => Language::Ha,
            "hak" => Language::Hak,
            "haw" => Language::Haw,
            "he" => Language::He,
            "hi" => Language::Hi,
            "hil" => Language::Hil,
            "hit" => Language::Hit,
            "hnd" => Language::Hnd,
            "hr" => Language::Hr,
            "hsb" => Language::Hsb,
            "ht" => Language::Ht,
            "hu" => Language::Hu,
            "hy" => Language::Hy,
            "ia" => Language::Ia,
            "id" => Language::Id,
            "ie" => Language::Ie,
            "ig" => Language::Ig,
            "ilo" => Language::Ilo,
            "inh" => Language::Inh,
            "io" => Language::Io,
            "is" => Language::Is,
            "it" => Language::It,
            "iu" => Language::Iu,
            "izh" => Language::Izh,
            "ja" => Language::Ja,
            "jbo" => Language::Jbo,
            "jpa" => Language::Jpa,
            "jv" => Language::Jv,
            "ka" => Language::Ka,
            "kaa" => Language::Kaa,
            "kab" => Language::Kab,
            "kea" => Language::Kea,
            "kim" => Language::Kim,
            "kjh" => Language::Kjh,
            "kk" => Language::Kk,
            "kl" => Language::Kl,
            "km" => Language::Km,
            "kn" => Language::Kn,
            "ko" => Language::Ko,
            "kok" => Language::Kok,
            "kos" => Language::Kos,
            "krl" => Language::Krl,
            "ku" => Language::Ku,
            "kv" => Language::Kv,
            "kw" => Language::Kw,
            "ky" => Language::Ky,
            "la" => Language::La,
            "lad" => Language::Lad,
            "lad-Cyrl" => Language::LadCyrl,
            "lad-Hebr" => Language::LadHebr,
            "lad-Latn" => Language::LadLatn,
            "lb" => Language::Lb,
            "lbe" => Language::Lbe,
            "lg" => Language::Lg,
            "li" => Language::Li,
            "lij" => Language::Lij,
            "liv" => Language::Liv,
            "lld" => Language::Lld,
            "lmo" => Language::Lmo,
            "ln" => Language::Ln,
            "lo" => Language::Lo,
            "lt" => Language::Lt,
            "ltg" => Language::Ltg,
            "lv" => Language::Lv,
            "mas" => Language::Mas,
            "mdf" => Language::Mdf,
            "mg" => Language::Mg,
            "mh" => Language::Mh,
            "mi" => Language::Mi,
            "mk" => Language::Mk,
            "ml" => Language::Ml,
            "mn" => Language::Mn,
            "mnc" => Language::Mnc,
            "mr" => Language::Mr,
            "mrh" => Language::Mrh,
            "ms" => Language::Ms,
            "mt" => Language::Mt,
            "mwl" => Language::Mwl,
            "mww" => Language::Mww,
            "my" => Language::My,
            "myv" => Language::Myv,
            "na" => Language::Na,
            "nah" => Language::Nah,
            "nan" => Language::Nan,
            "nap" => Language::Nap,
            "nb" => Language::Nb,
            "nci" => Language::Nci,
            "nds" => Language::Nds,
            "ne" => Language::Ne,
            "ng" => Language::Ng,
            "nij" => Language::Nij,
            "niu" => Language::Niu,
            "nl" => Language::Nl,
            "nn" => Language::Nn,
            "no" => Language::No,
            "nov" => Language::Nov,
            "nrf" => Language::Nrf,
            "nso" => Language::Nso,
            "nv" => Language::Nv,
            "ny" => Language::Ny,
            "oc" => Language::Oc,
            "oj" => Language::Oj,
            "om" => Language::Om,
            "or" => Language::Or,
            "os" => Language::Os,
            "pa" => Language::Pa,
            "pam" => Language::Pam,
            "pap" => Language::Pap,
            "pau" => Language::Pau,
            "pl" => Language::Pl,
            "pms" => Language::Pms,
            "pnb" => Language::Pnb,
            "pon" => Language::Pon,
            "pox" => Language::Pox,
            "prg" => Language::Prg,
            "ps" => Language::Ps,
            "pt" => Language::Pt,
            "qu" => Language::Qu,
            "rap" => Language::Rap,
            "rar" => Language::Rar,
            "rm" => Language::Rm,
            "rmy" => Language::Rmy,
            "rn" => Language::Rn,
            "ro" => Language::Ro,
            "rom" => Language::Rom,
            "rtm" => Language::Rtm,
            "ru" => Language::Ru,
            "rue" => Language::Rue,
            "rup" => Language::Rup,
            "rw" => Language::Rw,
            "ryu" => Language::Ryu,
            "sa" => Language::Sa,
            "sah" => Language::Sah,
            "sc" => Language::Sc,
            "scn" => Language::Scn,
            "sco" => Language::Sco,
            "sd" => Language::Sd,
            "se" => Language::Se,
            "sgd" => Language::Sgd,
            "sgs" => Language::Sgs,
            "sh" => Language::Sh,
            "si" => Language::Si,
            "sk" => Language::Sk,
            "sl" => Language::Sl,
            "sli" => Language::Sli,
            "sm" => Language::Sm,
            "sn" => Language::Sn,
            "so" => Language::So,
            "sq" => Language::Sq,
            "sr" => Language::Sr,
            "sr-Cyrl" => Language::SrCyrl,
            "sr-Latn" => Language::SrLatn,
            "src" => Language::Src,
            "sro" => Language::Sro,
            "ss" => Language::Ss,
            "su" => Language::Su,
            "sux" => Language::Sux,
            "sv" => Language::Sv,
            "sw" => Language::Sw,
            "syr" => Language::Syr,
            "szl" => Language::Szl,
            "ta" => Language::Ta,
            "tah" => Language::Tah,
            "te" => Language::Te,
            "tg" => Language::Tg,
            "th" => Language::Th,
            "ti" => Language::Ti,
            "tk" => Language::Tk,
            "tkl" => Language::Tkl,
            "tl" => Language::Tl,
            "tlh" => Language::Tlh,
            "tmr" => Language::Tmr,
            "tn" => Language::Tn,
            "to" => Language::To,
            "tog" => Language::Tog,
            "tr" => Language::Tr,
            "ts" => Language::Ts,
            "tt" => Language::Tt,
            "tum" => Language::Tum,
            "tvl" => Language::Tvl,
            "tw" => Language::Tw,
            "ty" => Language::Ty,
            "tyv" => Language::Tyv,
            "udm" => Language::Udm,
            "ug" => Language::Ug,
            "uk" => Language::Uk,
            "ur" => Language::Ur,
            "uz" => Language::Uz,
            "vec" => Language::Vec,
            "vep" => Language::Vep,
            "vi" => Language::Vi,
            "vo" => Language::Vo,
            "vot" => Language::Vot,
            "vro" => Language::Vro,
            "wa" => Language::Wa,
            "wah" => Language::Wah,
            "war" => Language::War,
            "wo" => Language::Wo,
            "wym" => Language::Wym,
            "xal" => Language::Xal,
            "xcu" => Language::Xcu,
            "xh" => Language::Xh,
            "xmf" => Language::Xmf,
            "yi" => Language::Yi,
            "yo" => Language::Yo,
            "yue" => Language::Yue,
            "zh" => Language::Zh,
            "zu" => Language::Zu,
            _ => return None,
        })
    }

    /// Returns the language corresponding to the given language name if any.
    pub fn from_name(name: &str) -> Option<Self> {
        Some(match name {
            "afarština" => Language::Aa,
            "abauština" => Language::Aau,
            "abcházština" => Language::Ab,
            "abenakština" => Language::Abe,
            "adygejština" => Language::Ady,
            "afrikánština" => Language::Af,
            "ainština" => Language::Ain,
            "akanština" => Language::Ak,
            "aleutština" => Language::Ale,
            "alsaština" => Language::Als,
            "jižní altajština" => Language::Alt,
            "amharština" => Language::Am,
            "aragonština" => Language::An,
            "staroangličtina" => Language::Ang,
            "arabština" => Language::Ar,
            "aramejština" => Language::Arc,
            "araukánština" => Language::Arn,
            "egyptská arabština" => Language::Arz,
            "asámština" => Language::As,
            "asturština" => Language::Ast,
            "severní altajština" => Language::Atv,
            "ajmarština" => Language::Ay,
            "ázerbájdžánština" => Language::Az,
            "jižní ázerbájdžánština" => Language::Azb,
            "baškirština" => Language::Ba,
            "balúčština" => Language::Bal,
            "bavorština" => Language::Bar,
            "bikolanština" => Language::Bcl,
            "běloruština" => Language::Be,
            "bembština" => Language::Bem,
            "bulharština" => Language::Bg,
            "bislamština" => Language::Bi,
            "bandžárština" => Language::Bjn,
            "bambarština" => Language::Bm,
            "bengálština" => Language::Bn,
            "tibetština" => Language::Bo,
            "bišnuprijskomanipurština" => Language::Bpy,
            "bretonština" => Language::Br,
            "bosenština" => Language::Bs,
            "burjatština" => Language::Bxr,
            "katalánština" => Language::Ca,
            "garífuna" => Language::Cab,
            "čečenština" => Language::Ce,
            "cebuánština" => Language::Ceb,
            "čamorština" => Language::Ch,
            "čukština" => Language::Chk,
            "čipevajština" => Language::Chp,
            "čerokézština" => Language::Chr,
            "cimbriština" => Language::Cim,
            "středokurdština" => Language::Ckb,
            "korsičtina" => Language::Co,
            "francouzská kreolština" => Language::Cpf,
            "kapiznonština" => Language::Cps,
            "krymská tatarština" => Language::Crh,
            "čeština" => Language::Cs,
            "kašubština" => Language::Csb,
            "staroslověnština" => Language::Cu,
            "čuvaština" => Language::Cv,
            "velština" => Language::Cy,
            "dánština" => Language::Da,
            "němčina" => Language::De,
            "dagaari dioulou" => Language::Dgd,
            "zarmština" => Language::Dje,
            "dalmatština" => Language::Dlm,
            "dolnolužická srbština" => Language::Dsb,
            "divehi (maledivština)" => Language::Dv,
            "dzongkä" => Language::Dz,
            "eveština" => Language::Ee,
            "starověká egyptština" => Language::Egy,
            "řečtina" => Language::El,
            "angličtina" => Language::En,
            "esperanto" => Language::Eo,
            "španělština" => Language::Es,
            "estonština" => Language::Et,
            "baskičtina" => Language::Eu,
            "extremadurština" => Language::Ext,
            "perština" => Language::Fa,
            "finština" => Language::Fi,
            "filipínština" => Language::Fil,
            "fidžijština" => Language::Fj,
            "kvenština" => Language::Fkv,
            "faerština" => Language::Fo,
            "francouzština" => Language::Fr,
            "franko-provensálština" => Language::Frp,
            "severofríština" => Language::Frr,
            "furlandština" => Language::Fur,
            "fríština" => Language::Fy,
            "irština" => Language::Ga,
            "gaddang" => Language::Gad,
            "gagauzština" => Language::Gag,
            "skotská gaelština" => Language::Gd,
            "kiribatština" => Language::Gil,
            "galicijština" => Language::Gl,
            "střední horní němčina" => Language::Gmh,
            "střední dolní němčina" => Language::Gml,
            "guaranština" => Language::Gn,
            "gótština" => Language::Got,
            "starořečtina" => Language::Grc,
            "švýcarská němčina" => Language::Gsw,
            "gudžarátština" => Language::Gu,
            "gusiština" => Language::Guz,
            "manština" => Language::Gv,
            "hauština" => Language::Ha,
            "hakka" => Language::Hak,
            "havajština" => Language::Haw,
            "hebrejština" => Language::He,
            "hindština" => Language::Hi,
            "hiligajnonština" => Language::Hil,
            "chetitština" => Language::Hit,
            "hindko" => Language::Hnd,
            "chorvatština" => Language::Hr,
            "hornolužická srbština" => Language::Hsb,
            "haitština" => Language::Ht,
            "maďarština" => Language::Hu,
            "arménština" => Language::Hy,
            "interlingua" => Language::Ia,
            "indonéština" => Language::Id,
            "interlingue" => Language::Ie,
            "igboština" => Language::Ig,
            "ilokánština" => Language::Ilo,
            "inguština" => Language::Inh,
            "ido" => Language::Io,
            "islandština" => Language::Is,
            "italština" => Language::It,
            "inuktitutština" => Language::Iu,
            "ingrijština" => Language::Izh,
            "japonština" => Language::Ja,
            "lojban" => Language::Jbo,
            "židovská palestinská aramejština" => Language::Jpa,
            "javánština" => Language::Jv,
            "gruzínština" => Language::Ka,
            "karakalpačtina" => Language::Kaa,
            "kabylština" => Language::Kab,
            "kapverdská kreolština" => Language::Kea,
            "tofalarština" => Language::Kim,
            "chakaština" => Language::Kjh,
            "kazaština" => Language::Kk,
            "grónština" => Language::Kl,
            "khmerština" => Language::Km,
            "kannadština" => Language::Kn,
            "korejština" => Language::Ko,
            "konkánština" => Language::Kok,
            "kosrajština" => Language::Kos,
            "karelština" => Language::Krl,
            "kurdština" => Language::Ku,
            "komijština" => Language::Kv,
            "kornština" => Language::Kw,
            "kyrgyzština" => Language::Ky,
            "latina" => Language::La,
            "ladino" => Language::Lad,
            "ladino (cyrilice)" => Language::LadCyrl,
            "ladino (hebrejské písmo)" => Language::LadHebr,
            "ladino (latinka)" => Language::LadLatn,
            "lucemburština" => Language::Lb,
            "lakština" => Language::Lbe,
            "lugandština" => Language::Lg,
            "limburština" => Language::Li,
            "ligurština" => Language::Lij,
            "livonština" => Language::Liv,
            "ladinština" => Language::Lld,
            "lombardština" => Language::Lmo,
            "lingalština" => Language::Ln,
            "laoština" => Language::Lo,
            "litevština" => Language::Lt,
            "latgalština" => Language::Ltg,
            "lotyština" => Language::Lv,
            "masajština" => Language::Mas,
            "mokša" => Language::Mdf,
            "malgaština" => Language::Mg,
            "maršálština" => Language::Mh,
            "maorština" => Language::Mi,
            "makedonština" => Language::Mk,
            "malajálamština" => Language::Ml,
            "mongolština" => Language::Mn,
            "mandžuština" => Language::Mnc,
            "maráthština" => Language::Mr,
            "mara" => Language::Mrh,
            "malajština" => Language::Ms,
            "maltština" => Language::Mt,
            "mirandština" => Language::Mwl,
            "bíla hmongština" => Language::Mww,
            "barmština" => Language::My,
            "erzja" => Language::Myv,
            "naurština" => Language::Na,
            "aztéčtina" => Language::Nah,
            "jižní min" => Language::Nan,
            "neapolština" => Language::Nap,
            "norština (bokmål)" => Language::Nb,
            "klasický nahuatl" => Language::Nci,
            "dolnoněmčina" => Language::Nds,
            "nepálština" => Language::Ne,
            "ndondština" => Language::Ng,
            "ngadžuština" => Language::Nij,
            "niueština" => Language::Niu,
            "nizozemština" => Language::Nl,
            "norština (nynorsk)" => Language::Nn,
            "norština" => Language::No,
            "novial" => Language::Nov,
            "guernseyština" => Language::Nrf,
            "severní sotština" => Language::Nso,
            "navaho" => Language::Nv,
            "čičevština" => Language::Ny,
            "okcitánština" => Language::Oc,
            "odžibvejština" => Language::Oj,
            "oromo" => Language::Om,
            "urijština" => Language::Or,
            "osetština" => Language::Os,
            "pandžábština" => Language::Pa,
            "pampangau" => Language::Pam,
            "papiamentština" => Language::Pap,
            "palauština" => Language::Pau,
            "polština" => Language::Pl,
            "piemontština" => Language::Pms,
            "paňdžábština (shahmukhi)" => Language::Pnb,
            "pohnpeiština" => Language::Pon,
            "polabština" => Language::Pox,
            "pruština" => Language::Prg,
            "paštunština" => Language::Ps,
            "portugalština" => Language::Pt,
            "kečuánština" => Language::Qu,
            "rapanuiština" => Language::Rap,
            "rarotongština" => Language::Rar,
            "rétorománština" => Language::Rm,
            "vlašská romština" => Language::Rmy,
            "kirundi" => Language::Rn,
            "rumunština" => Language::Ro,
            "romština" => Language::Rom,
            "rotumanština" => Language::Rtm,
            "ruština" => Language::Ru,
            "rusínština" => Language::Rue,
            "arumunština" => Language::Rup,
            "rwandština" => Language::Rw,
            "okinawština" => Language::Ryu,
            "sanskrt" => Language::Sa,
            "jakutština" => Language::Sah,
            "sardinština" => Language::Sc,
            "sicilština" => Language::Scn,
            "skotština" => Language::Sco,
            "sindhština" => Language::Sd,
            "severní sámština" => Language::Se,
            "surigaononština" => Language::Sgd,
            "žemaitština" => Language::Sgs,
            "srbochorvatština" => Language::Sh,
            "sinhálština" => Language::Si,
            "slovenština" => Language::Sk,
            "slovinština" => Language::Sl,
            "slezská němčina" => Language::Sli,
            "samojština" => Language::Sm,
            "šonština" => Language::Sn,
            "somálština" => Language::So,
            "albánština" => Language::Sq,
            "srbština" => Language::Sr,
            "srbština (cyrilice)" => Language::SrCyrl,
            "srbština (latinka)" => Language::SrLatn,
            "lugudorská sardinština" => Language::Src,
            "siswatština" => Language::Ss,
            "sundánština" => Language::Su,
            "sumerština" => Language::Sux,
            "švédština" => Language::Sv,
            "svahilština" => Language::Sw,
            "syrština" => Language::Syr,
            "slezština" => Language::Szl,
            "tamilština" => Language::Ta,
            "telugština" => Language::Te,
            "tádžičtina" => Language::Tg,
            "thajština" => Language::Th,
            "tigrinijština" => Language::Ti,
            "turkmenština" => Language::Tk,
            "tokelauština" => Language::Tkl,
            "tagalština" => Language::Tl,
            "klingonština" => Language::Tlh,
            "židovská babylonská aramejština" => Language::Tmr,
            "setswanština" => Language::Tn,
            "tongánština" => Language::To,
            "malavská tongština" => Language::Tog,
            "turečtina" => Language::Tr,
            "tsonga" => Language::Ts,
            "tatarština" => Language::Tt,
            "tumbučtina" => Language::Tum,
            "tuvalština" => Language::Tvl,
            "ťwiština" => Language::Tw,
            "tahitština" => Language::Ty,
            "tuvinština" => Language::Tyv,
            "udmurtština" => Language::Udm,
            "ujgurština" => Language::Ug,
            "ukrajinština" => Language::Uk,
            "urdština" => Language::Ur,
            "uzbečtina" => Language::Uz,
            "benátština" => Language::Vec,
            "vepština" => Language::Vep,
            "vietnamština" => Language::Vi,
            "volapük" => Language::Vo,
            "votština" => Language::Vot,
            "võruština" => Language::Vro,
            "valonština" => Language::Wa,
            "watubela" => Language::Wah,
            "warajština" => Language::War,
            "wolofština" => Language::Wo,
            "vilamovština" => Language::Wym,
            "kalmyčtina" => Language::Xal,
            "kurština" => Language::Xcu,
            "xhoština" => Language::Xh,
            "mingrelština" => Language::Xmf,
            "jidiš" => Language::Yi,
            "jorubština" => Language::Yo,
            "kantonština" => Language::Yue,
            "čínština" => Language::Zh,
            "zuluština" => Language::Zu,
            _ => return None,
        })
    }

    /// Returns the language code for the language.
    pub fn language_code(self) -> &'static str {
        match self {
            Language::Aa => "aa",
            Language::Aau => "aau",
            Language::Ab => "ab",
            Language::Abe => "abe",
            Language::Ady => "ady",
            Language::Af => "af",
            Language::Ain => "ain",
            Language::Ak => "ak",
            Language::Ale => "ale",
            Language::Als => "als",
            Language::Alt => "alt",
            Language::Am => "am",
            Language::An => "an",
            Language::Ang => "ang",
            Language::Ar => "ar",
            Language::Arc => "arc",
            Language::Arn => "arn",
            Language::Arz => "arz",
            Language::As => "as",
            Language::Ast => "ast",
            Language::Atv => "atv",
            Language::Ay => "ay",
            Language::Az => "az",
            Language::Azb => "azb",
            Language::Ba => "ba",
            Language::Bal => "bal",
            Language::Bar => "bar",
            Language::Bcl => "bcl",
            Language::Be => "be",
            Language::Bem => "bem",
            Language::Bg => "bg",
            Language::Bi => "bi",
            Language::Bjn => "bjn",
            Language::Bm => "bm",
            Language::Bn => "bn",
            Language::Bo => "bo",
            Language::Bpy => "bpy",
            Language::Br => "br",
            Language::Bs => "bs",
            Language::Bxr => "bxr",
            Language::Ca => "ca",
            Language::Cab => "cab",
            Language::Ce => "ce",
            Language::Ceb => "ceb",
            Language::Ch => "ch",
            Language::Chk => "chk",
            Language::Chp => "chp",
            Language::Chr => "chr",
            Language::Cim => "cim",
            Language::Ckb => "ckb",
            Language::Co => "co",
            Language::Cpf => "cpf",
            Language::Cps => "cps",
            Language::Crh => "crh",
            Language::Cs => "cs",
            Language::Csb => "csb",
            Language::Cu => "cu",
            Language::Cv => "cv",
            Language::Cy => "cy",
            Language::Da => "da",
            Language::De => "de",
            Language::Dgd => "dgd",
            Language::Dje => "dje",
            Language::Dlm => "dlm",
            Language::Dsb => "dsb",
            Language::Dv => "dv",
            Language::Dz => "dz",
            Language::Ee => "ee",
            Language::Egy => "egy",
            Language::El => "el",
            Language::En => "en",
            Language::Eo => "eo",
            Language::Es => "es",
            Language::Et => "et",
            Language::Eu => "eu",
            Language::Ext => "ext",
            Language::Fa => "fa",
            Language::Fi => "fi",
            Language::Fil => "fil",
            Language::Fj => "fj",
            Language::Fkv => "fkv",
            Language::Fo => "fo",
            Language::Fr => "fr",
            Language::Frp => "frp",
            Language::Frr => "frr",
            Language::Fur => "fur",
            Language::Fy => "fy",
            Language::Ga => "ga",
            Language::Gad => "gad",
            Language::Gag => "gag",
            Language::Gd => "gd",
            Language::Gil => "gil",
            Language::Gl => "gl",
            Language::Gmh => "gmh",
            Language::Gml => "gml",
            Language::Gn => "gn",
            Language::Got => "got",
            Language::Grc => "grc",
            Language::Gsw => "gsw",
            Language::Gu => "gu",
            Language::Guz => "guz",
            Language::Gv => "gv",
            Language::Ha => "ha",
            Language::Hak => "hak",
            Language::Haw => "haw",
            Language::He => "he",
            Language::Hi => "hi",
            Language::Hil => "hil",
            Language::Hit => "hit",
            Language::Hnd => "hnd",
            Language::Hr => "hr",
            Language::Hsb => "hsb",
            Language::Ht => "ht",
            Language::Hu => "hu",
            Language::Hy => "hy",
            Language::Ia => "ia",
            Language::Id => "id",
            Language::Ie => "ie",
            Language::Ig => "ig",
            Language::Ilo => "ilo",
            Language::Inh => "inh",
            Language::Io => "io",
            Language::Is => "is",
            Language::It => "it",
            Language::Iu => "iu",
            Language::Izh => "izh",
            Language::Ja => "ja",
            Language::Jbo => "jbo",
            Language::Jpa => "jpa",
            Language::Jv => "jv",
            Language::Ka => "ka",
            Language::Kaa => "kaa",
            Language::Kab => "kab",
            Language::Kea => "kea",
            Language::Kim => "kim",
            Language::Kjh => "kjh",
            Language::Kk => "kk",
            Language::Kl => "kl",
            Language::Km => "km",
            Language::Kn => "kn",
            Language::Ko => "ko",
            Language::Kok => "kok",
            Language::Kos => "kos",
            Language::Krl => "krl",
            Language::Ku => "ku",
            Language::Kv => "kv",
            Language::Kw => "kw",
            Language::Ky => "ky",
            Language::La => "la",
            Language::Lad => "lad",
            Language::LadCyrl => "lad-Cyrl",
            Language::LadHebr => "lad-Hebr",
            Language::LadLatn => "lad-Latn",
            Language::Lb => "lb",
            Language::Lbe => "lbe",
            Language::Lg => "lg",
            Language::Li => "li",
            Language::Lij => "lij",
            Language::Liv => "liv",
            Language::Lld => "lld",
            Language::Lmo => "lmo",
            Language::Ln => "ln",
            Language::Lo => "lo",
            Language::Lt => "lt",
            Language::Ltg => "ltg",
            Language::Lv => "lv",
            Language::Mas => "mas",
            Language::Mdf => "mdf",
            Language::Mg => "mg",
            Language::Mh => "mh",
            Language::Mi => "mi",
            Language::Mk => "mk",
            Language::Ml => "ml",
            Language::Mn => "mn",
            Language::Mnc => "mnc",
            Language::Mr => "mr",
            Language::Mrh => "mrh",
            Language::Ms => "ms",
            Language::Mt => "mt",
            Language::Mwl => "mwl",
            Language::Mww => "mww",
            Language::My => "my",
            Language::Myv => "myv",
            Language::Na => "na",
            Language::Nah => "nah",
            Language::Nan => "nan",
            Language::Nap => "nap",
            Language::Nb => "nb",
            Language::Nci => "nci",
            Language::Nds => "nds",
            Language::Ne => "ne",
            Language::Ng => "ng",
            Language::Nij => "nij",
            Language::Niu => "niu",
            Language::Nl => "nl",
            Language::Nn => "nn",
            Language::No => "no",
            Language::Nov => "nov",
            Language::Nrf => "nrf",
            Language::Nso => "nso",
            Language::Nv => "nv",
            Language::Ny => "ny",
            Language::Oc => "oc",
            Language::Oj => "oj",
            Language::Om => "om",
            Language::Or => "or",
            Language::Os => "os",
            Language::Pa => "pa",
            Language::Pam => "pam",
            Language::Pap => "pap",
            Language::Pau => "pau",
            Language::Pl => "pl",
            Language::Pms => "pms",
            Language::Pnb => "pnb",
            Language::Pon => "pon",
            Language::Pox => "pox",
            Language::Prg => "prg",
            Language::Ps => "ps",
            Language::Pt => "pt",
            Language::Qu => "qu",
            Language::Rap => "rap",
            Language::Rar => "rar",
            Language::Rm => "rm",
            Language::Rmy => "rmy",
            Language::Rn => "rn",
            Language::Ro => "ro",
            Language::Rom => "rom",
            Language::Rtm => "rtm",
            Language::Ru => "ru",
            Language::Rue => "rue",
            Language::Rup => "rup",
            Language::Rw => "rw",
            Language::Ryu => "ryu",
            Language::Sa => "sa",
            Language::Sah => "sah",
            Language::Sc => "sc",
            Language::Scn => "scn",
            Language::Sco => "sco",
            Language::Sd => "sd",
            Language::Se => "se",
            Language::Sgd => "sgd",
            Language::Sgs => "sgs",
            Language::Sh => "sh",
            Language::Si => "si",
            Language::Sk => "sk",
            Language::Sl => "sl",
            Language::Sli => "sli",
            Language::Sm => "sm",
            Language::Sn => "sn",
            Language::So => "so",
            Language::Sq => "sq",
            Language::Sr => "sr",
            Language::SrCyrl => "sr-Cyrl",
            Language::SrLatn => "sr-Latn",
            Language::Src => "src",
            Language::Sro => "sro",
            Language::Ss => "ss",
            Language::Su => "su",
            Language::Sux => "sux",
            Language::Sv => "sv",
            Language::Sw => "sw",
            Language::Syr => "syr",
            Language::Szl => "szl",
            Language::Ta => "ta",
            Language::Tah => "tah",
            Language::Te => "te",
            Language::Tg => "tg",
            Language::Th => "th",
            Language::Ti => "ti",
            Language::Tk => "tk",
            Language::Tkl => "tkl",
            Language::Tl => "tl",
            Language::Tlh => "tlh",
            Language::Tmr => "tmr",
            Language::Tn => "tn",
            Language::To => "to",
            Language::Tog => "tog",
            Language::Tr => "tr",
            Language::Ts => "ts",
            Language::Tt => "tt",
            Language::Tum => "tum",
            Language::Tvl => "tvl",
            Language::Tw => "tw",
            Language::Ty => "ty",
            Language::Tyv => "tyv",
            Language::Udm => "udm",
            Language::Ug => "ug",
            Language::Uk => "uk",
            Language::Ur => "ur",
            Language::Uz => "uz",
            Language::Vec => "vec",
            Language::Vep => "vep",
            Language::Vi => "vi",
            Language::Vo => "vo",
            Language::Vot => "vot",
            Language::Vro => "vro",
            Language::Wa => "wa",
            Language::Wah => "wah",
            Language::War => "war",
            Language::Wo => "wo",
            Language::Wym => "wym",
            Language::Xal => "xal",
            Language::Xcu => "xcu",
            Language::Xh => "xh",
            Language::Xmf => "xmf",
            Language::Yi => "yi",
            Language::Yo => "yo",
            Language::Yue => "yue",
            Language::Zh => "zh",
            Language::Zu => "zu",
        }
    }
}
